server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://NTHIANHTHU\SQLEXPRESS:1434;databaseName=Student
    username: sa
    password: sa2018@anhthu
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

