server:
  port: 8888

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=Student
    username: sa
    password: sa2018@anhthu
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

